from enum import Enum

class Blender_BS(Enum):
    Basis = 0
    mouthOpen = 1
    mouthSmile = 2
    eyeBlinkLeft = 3
    eyeLookDownLeft = 4
    eyeLookInLeft = 5
    eyeLookOutLeft = 6
    eyeLookUpLeft = 7
    eyeSquintLeft = 8
    eyeWideLeft = 9
    eyeBlinkRight = 10
    eyeLookDownRight = 11
    eyeLookInRight = 12
    eyeLookOutRight = 13
    eyeLookUpRight = 14
    eyeSquintRight = 15
    eyeWideRight = 16
    jawForward = 17
    jawLeft = 18
    jawRight = 19
    jawOpen = 20
    mouthClose = 21
    mouthFunnel = 22
    mouthPucker = 23
    mouthRight = 24
    mouthLeft = 25
    mouthSmileLeft = 26
    mouthSmileRight = 27
    mouthFrownRight = 28
    mouthFrownLeft = 29
    mouthDimpleLeft = 30
    mouthDimpleRight = 31
    mouthStretchLeft = 32
    mouthStretchRight = 33
    mouthRollLower = 34
    mouthRollUpper = 35
    mouthShrugLower = 36
    mouthShrugUpper = 37
    mouthPressLeft = 38
    mouthPressRight = 39
    mouthLowerDownLeft = 40
    mouthLowerDownRight = 41
    mouthUpperUpLeft = 42
    mouthUpperUpRight = 43
    browDownLeft = 44
    browDownRight = 45
    browInnerUp = 46
    browOuterUpLeft = 47
    browOuterUpRight = 48
    cheekPuff = 49
    cheekSquintLeft = 50
    cheekSquintRight = 51
    noseSneerLeft = 52
    noseSneerRight = 53
    tongueOut = 54

    # 定义mediapipe_bs字典
class Mediapipe_BS(Enum):
    browDownLeft = 0
    browDownRight = 1
    browInnerUp = 2
    browOuterUpLeft = 3
    browOuterUpRight = 4
    cheekPuff = 5
    cheekSquintLeft = 6
    cheekSquintRight = 7
    eyeBlinkLeft = 8
    eyeBlinkRight = 9
    eyeLookDownLeft = 10
    eyeLookDownRight = 11
    eyeLookInLeft = 12
    eyeLookInRight = 13
    eyeLookOutLeft = 14
    eyeLookOutRight = 15
    eyeLookUpLeft = 16
    eyeLookUpRight = 17
    eyeSquintLeft = 18
    eyeSquintRight = 19
    eyeWideLeft = 20
    eyeWideRight = 21
    jawForward = 22
    jawLeft = 23
    jawOpen = 24
    jawRight = 25
    mouthClose = 26
    mouthDimpleLeft = 27
    mouthDimpleRight = 28
    mouthFrownLeft = 29
    mouthFrownRight = 30
    mouthFunnel = 31
    mouthLeft = 32
    mouthLowerDownLeft = 33
    mouthLowerDownRight = 34
    mouthPressLeft = 35
    mouthPressRight = 36
    mouthPucker = 37
    mouthRight = 38
    mouthRollLower = 39
    mouthRollUpper = 40
    mouthShrugLower = 41
    mouthShrugUpper = 42
    mouthSmileLeft = 43
    mouthSmileRight = 44
    mouthStretchLeft = 45
    mouthStretchRight = 46
    mouthUpperUpLeft = 47
    mouthUpperUpRight = 48
    noseSneerLeft = 49
    noseSneerRight = 50
    tongueOut = 51

class Pico_BS(Enum):
    EyeLookDown_L=0, 
    NoseSneer_L=1, 
    EyeLookIn_L=2, 
    BrowInnerUp=3, 
    BrowDown_R=4, 
    MouthClose=5, 
    MouthLowerDown_R=6, 
    JawOpen=7, 
    MouthUpperUp_R=8, 
    MouthShrugUpper=9, 
    MouthFunnel=10, 
    EyeLookIn_R=11, 
    EyeLookDown_R=12, 
    NoseSneer_R=13, 
    MouthRollUpper=14, 
    JawRight=15, 
    BrowDown_L=16, 
    MouthShrugLower=17, 
    MouthRollLower=18, 
    MouthSmile_L=19, 
    MouthPress_L=20, 
    MouthSmile_R=21, 
    MouthPress_R=22, 
    MouthDimple_R=23, 
    MouthLeft=24, 
    JawForward=25, 
    EyeSquint_L=26, 
    MouthFrown_L=27, 
    EyeBlink_L=28, 
    CheekSquint_L=29, 
    BrowOuterUp_L=30, 
    EyeLookUp_L=31, 
    JawLeft=32, 
    MouthStretch_L=33, 
    MouthPucker=34, 
    EyeLookUp_R=35, 
    BrowOuterUp_R=36, 
    CheekSquint_R=37, 
    EyeBlink_R=38, 
    MouthUpperUp_L=39, 
    MouthFrown_R=40, 
    EyeSquint_R=41, 
    MouthStretch_R=42, 
    CheekPuff=43, 
    EyeLookOut_L=44, 
    EyeLookOut_R=45, 
    EyeWide_R=46, 
    EyeWide_L=47, 
    MouthRight=48, 
    MouthDimple_L=49, 
    MouthLowerDown_L=50, 
    TongueOut=51,
    PP=52,
    CH=53,
    o=54, 
    O=55, 
    I=56, 
    u=57, 
    RR=58, 
    XX=59, 
    aa=60, 
    i=61, 
    FF=62, 
    U=63, 
    TH=64, 
    kk=65, 
    SS=66, 
    e=67, 
    DD=68, 
    E=69, 
    nn=70, 
    sil=71 

class Arkit_BS(Enum):
    EyeBlinkLeft = 0
    EyeLookDownLeft = 1
    EyeLookInLeft = 2
    EyeLookOutLeft = 3
    EyeLookUpLeft = 4
    EyeSquintLeft = 5
    EyeWideLeft = 6
    EyeBlinkRight = 7
    EyeLookDownRight = 8
    EyeLookInRight = 9
    EyeLookOutRight = 10
    EyeLookUpRight = 11
    EyeSquintRight = 12
    EyeWideRight = 13
    JawForward = 14
    JawLeft = 15
    JawRight = 16
    JawOpen = 17
    MouthClose = 18
    MouthFunnel = 19
    MouthPucker = 20
    MouthLeft = 21
    MouthRight = 22
    MouthSmileLeft = 23
    MouthSmileRight = 24
    MouthFrownLeft = 25
    MouthFrownRight = 26
    MouthDimpleLeft = 27
    MouthDimpleRight = 28
    MouthStretchLeft = 29
    MouthStretchRight = 30
    MouthRollLower = 31
    MouthRollUpper = 32
    MouthShrugLower = 33
    MouthShrugUpper = 34
    MouthPressLeft = 35
    MouthPressRight = 36
    MouthLowerDownLeft = 37
    MouthLowerDownRight = 38
    MouthUpperUpLeft = 39
    MouthUpperUpRight = 40
    BrowDownLeft = 41
    BrowDownRight = 42
    BrowInnerUp = 43
    BrowOuterUpLeft = 44
    BrowOuterUpRight = 45
    CheekPuff = 46
    CheekSquintLeft = 47
    CheekSquintRight = 48
    NoseSneerLeft = 49
    NoseSneerRight = 50
    TongueOut = 51
    HeadYaw = 52
    HeadPitch = 53
    HeadRoll = 54
    LeftEyeYaw = 55
    LeftEyePitch = 56
    LeftEyeRoll = 57
    RightEyeYaw = 58
    RightEyePitch = 59
    RightEyeRoll = 60